### ISSUE TITLE
RuntimeError: Please export CSV with Saldo! - Existing Saldo Row

### ISSUE THREAD

**Issue by kraftvital** [fabolhak/ofxstatement-de-ing#2]
I am getting the following error, although there is a Saldo row:

Traceback (most recent call last):
  File "/usr/bin/ofxstatement", line 33, in <module>
    sys.exit(load_entry_point('ofxstatement==0.7.1', 'console_scripts', 'ofxstatement')())
  File "/usr/lib/python3/dist-packages/ofxstatement/tool.py", line 198, in run
    return args.func(args)
  File "/usr/lib/python3/dist-packages/ofxstatement/tool.py", line 169, in convert
    statement = parser.parse()
  File "/usr/lib/python3/dist-packages/ofxstatement/plugins/ingde.py", line 58, in parse
    raise RuntimeError('Please export CSV with Saldo!')
RuntimeError: Please export CSV with Saldo!

**Comment by kraftvital** [comment]
I would like to add that I couldnt find any differences in the format with the files in the tests.

Thanks in advance!

LG
Mario :)

**Comment by fabolhak** [comment]
Hello, sorry for the late response. The export format seems to have changed. I had some time to make the plugin working again. Can you please try again? :)

**Comment by fabolhak** [comment]
please reopen if problem still exists
